Refactor (#173)
* move error messages to seperate file.

* move error messages to seperate file

* move all lists from helpers and config to lists.r

* move lists from checks to lists.r

* remove unused functions

* remove unused tests

* lint all files

* remove used auto_manage config from config

* move draw parameters and create random seeds from checks to helpers.

* add function for creating calibration acceptance rate print statements only print stats being used.

* update calibrate to use new print function.

* remove tests for removed helpers

* make tests between 0 and 1 for gamma paramater inclusive of 0 and 1.

* remove unused helpers

* add .lintr file

* test new github actions lintr

* Update README.md

Update lint badge. 
Updated author list to match pops core rules for author vs. contributor.

* Update CHANGELOG.md

* remove old lint workflow

* remove commented code linter from lintr until #174 is resolved.

* add updating of quantity and allocation calibration

* test simplified github r cmd actions workflow

* add renv workflow to r cmd checks

* remove sp dependacy by changing movements check

* add gdal and proj to macos rcmd check workflow

* update test coverage github workflow.

diff --git a/.github/workflows/test-coverage.yaml b/.github/workflows/test-coverage.yaml
--- a/.github/workflows/test-coverage.yaml
+++ b/.github/workflows/test-coverage.yaml
@@ -1,53 +1,52 @@
+# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
-    branches:
-      - main
+    branches: [main, master]
   pull_request:
-    branches:
-      - main
+    branches: [main, master]
 
 name: test-coverage
 
 jobs:
   test-coverage:
     runs-on: ubuntu-latest
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@v3
 
       - uses: r-lib/actions/setup-r@v2
-
-      - uses: r-lib/actions/setup-pandoc@v2
         with:
-          pandoc-version: '2.7.3'
+          use-public-rspm: true
 
-      - name: install gdal
-        run: |
-          # install spatial dependencies
-          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
-          sudo apt update
-          sudo apt install \
-            libudunits2-dev \
-            libgdal-dev \
-            libgeos-dev \
-            libproj-dev \
-            libharfbuzz-dev \
-            libfribidi-dev
+      - uses: r-lib/actions/setup-renv@v2
 
-      - name: Install renv
-        shell: Rscript {0}
-        run: |
-          install.packages("renv")
-
-      - uses: actions/cache@v2
+      - uses: r-lib/actions/setup-r-dependencies@v2
         with:
-          path: ~/Library/Application Support/renv
-          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
-          restore-keys: |
-            ${{ runner.os }}-renv-
+          extra-packages: any::covr
+          needs: coverage
 
       - name: Test coverage
-        shell: Rscript {0}
         run: |
-          renv::restore()
-          covr::codecov()
+          covr::codecov(
+            quiet = FALSE,
+            clean = FALSE,
+            install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
+          )
+        shell: Rscript {0}
 
+      - name: Show testthat output
+        if: always()
+        run: |
+          ## --------------------------------------------------------------------
+          find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
+        shell: bash
+
+      - name: Upload test results
+        if: failure()
+        uses: actions/upload-artifact@v3
+        with:
+          name: coverage-test-failures
+          path: ${{ runner.temp }}/package
